# Generated by Django 4.2.5 on 2023-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('Lecture_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Faculty_Name', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
