# Generated by Django 4.2.5 on 2023-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='college',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
