# Generated by Django 4.2.5 on 2023-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_booking_branch_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='college',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
