# Generated by Django 4.2.5 on 2023-09-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_booking_branch_alter_booking_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='college',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
